"""Collect every harness record under results/bench/ into one table (results/bench/SUMMARY.md + summary.csv) for filling the paper tables.

Columns follow tab:main / tab:noref / tab:recon: per (method, controller, split, condition, res) the adherence numbers and the quality block.
Also prints the efficiency rows from results/bench/efficiency.json if present.
"""
import csv
import glob
import json
from pathlib import Path

from common import REPO_BENCH

R = REPO_BENCH.parent / "results" / "bench"
merged = {}


def variant(fname: str, rec: dict) -> tuple:
    """Records that must NOT merge with the default one: native-condition scoring (.cond2048 / adherence.cond_res), subset500 runs, and the
    upsampled dagger references (@<res>ref, field `via`). Returned as (cond_res, subset, via)."""
    cond_res = int(rec.get("adherence", {}).get("cond_res", 2048 if ".cond2048" in fname else 512))
    subset = "subset500" if ".subset500" in fname else ""
    via = "upsampled_ref" if ("ref." in fname or "ref_" in fname or rec.get("via")) else ""
    return cond_res, subset, via


for f in sorted(glob.glob(str(R / "*" / "*@*.json"))):      # default records first, then metric-subset files (e.g. *.vlm.json) merge into them
    for rec in json.load(open(f)):
        cond_res, subset, via = variant(Path(f).name, rec)
        key = (rec["split"], rec["method"], rec.get("controller", ""), rec["res"], rec["condition"], cond_res, subset, via)
        if key in merged:
            merged[key]["quality"].update(rec.get("quality", {}))
            if not merged[key].get("adherence"):
                merged[key]["adherence"] = rec.get("adherence", {})
        else:
            merged[key] = {**rec, "quality": dict(rec.get("quality", {})), "adherence": dict(rec.get("adherence", {})), "_cond_res": cond_res, "_subset": subset, "_via": via}
rows = []
for rec in merged.values():
    if True:
        q = rec.get("quality", {}); a = rec.get("adherence", {})
        rows.append({"split": rec["split"], "condition": rec["condition"], "method": rec["method"], "controller": rec.get("controller", ""),
                     "res": rec["res"], "cond_res": rec["_cond_res"], "subset": rec["_subset"], "via": rec["_via"], "n": rec["n"],
                     "f1": a.get("f1"), "mse": a.get("mse"), "rmse": a.get("rmse"), "miou": a.get("miou"), "sr": a.get("sr"),
                     "fid": q.get("fid"), "pfid": q.get("pfid"), "musiq": q.get("musiq"), "niqe": q.get("niqe"), "maniqa": q.get("maniqa"),
                     "qalign": q.get("qalign"), "deqa": q.get("deqa"), "unipercept_iaa": q.get("unipercept_iaa"), "unipercept_iqa": q.get("unipercept_iqa"),
                     "vqr1": q.get("vqr1"), "psnr": q.get("psnr"), "ssim": q.get("ssim"), "lpips": q.get("lpips"), "dists": q.get("dists")})
cols = list(rows[0].keys()) if rows else []
R.mkdir(parents=True, exist_ok=True)
with open(R / "summary.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=cols); w.writeheader(); w.writerows(rows)


def fmt(v, nd=3):
    if v is None:
        return ""
    return f"{v:.{nd}f}" if isinstance(v, float) else str(v)


lines = ["# Benchmark results summary (auto-generated by bench/assemble.py)", "",
         "| split | condition | method | ctrl | res | cond res | subset | via | n | F1 | MSE | RMSE | mIoU | SR | FID | pFID | MUSIQ | NIQE | MANIQA | Q-Align | DeQA | UniP-IAA | UniP-IQA | VQ-R1 | PSNR | SSIM | LPIPS | DISTS |",
         "|" + "---|" * 28]
for r in sorted(rows, key=lambda r: (r["split"], r["condition"], r["cond_res"], r["subset"], r["via"], r["res"], r["controller"], r["method"])):
    lines.append("| " + " | ".join([r["split"], r["condition"], r["method"], r["controller"], str(r["res"]), str(r["cond_res"]), r["subset"], r["via"], str(r["n"]),
                                    fmt(r["f1"], 4), fmt(r["mse"], 2), fmt(r["rmse"], 2), fmt(r["miou"], 2), fmt(r["sr"], 2), fmt(r["fid"], 2), fmt(r["pfid"], 2),
                                    fmt(r["musiq"], 2), fmt(r["niqe"], 3), fmt(r["maniqa"], 4), fmt(r["qalign"], 3), fmt(r["deqa"], 3), fmt(r["unipercept_iaa"], 3),
                                    fmt(r["unipercept_iqa"], 3), fmt(r["vqr1"], 3), fmt(r["psnr"], 2), fmt(r["ssim"], 4), fmt(r["lpips"], 4), fmt(r["dists"], 4)]) + " |")
eff = R / "efficiency.json"
if eff.exists():
    lines += ["", "## Efficiency (one H200, median over n images)", "", "| output | pipeline | gen res | gen steps | dec steps | gen s | dec s | latency s | peak GB | note |", "|---|---|---|---|---|---|---|---|---|---|"]
    for e in json.load(open(eff)):
        lines.append("| " + " | ".join([str(e.get("output")), e.get("pipeline", ""), str(e.get("gen_res")), str(e.get("gen_steps")), str(e.get("dec_steps")),
                                        fmt(e.get("gen_s"), 2), fmt(e.get("dec_s", e.get("vae_s")), 3), fmt(e.get("latency_s"), 2), fmt(e.get("peak_mem_gb"), 1), e.get("note", "")]) + " |")
(R / "SUMMARY.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
