"""Build BASELINES.md (repo root) + results/bench/baselines.json: the curated baseline numbers a CGD variant has to beat, read from the
harness records under results/bench/. Re-run after any new record: python bench/make_baselines.py

Sections: A main benchmark (512-generation, condition = 512 map; n = 5000 / 2000), B native-condition setting (condition = 2048 map),
C DreamBench subject rows, D condition-scale sweep (dev-200), E dev-200 gate, F student vs teacher (subset500, when present),
G efficiency, H the rule for "beating" a baseline. Dagger = bicubic x4 upsample of a 512-native output (interpolation route, not native).
"""
import csv
import glob
import json
from pathlib import Path

from common import REPO_BENCH

ROOT = REPO_BENCH.parent
R = ROOT / "results" / "bench"
CTRL = {"omini": "OminiControl", "easycontrol": "EasyControl", "fluxcn": "FLUX ControlNet Union-Pro-2.0"}


def variant(fname, rec):
    cond_res = int(rec.get("adherence", {}).get("cond_res", 2048 if ".cond2048" in fname else 512))
    subset = rec.get("subset") or ("subset500" if ".subset500" in fname else "")
    via = "ref" if (rec.get("via") or "@2048ref" in fname) else ""
    return cond_res, subset, via


recs = {}
for f in sorted(glob.glob(str(R / "*" / "*@*.json"))):
    for rec in json.load(open(f)):
        cond_res, subset, via = variant(Path(f).name, rec)
        key = (rec["split"], rec["condition"], rec.get("controller", ""), rec["method"], rec["res"], cond_res, subset, via)
        if key in recs:
            recs[key]["quality"].update(rec.get("quality", {}))
            if not recs[key]["adherence"]:
                recs[key]["adherence"] = dict(rec.get("adherence", {}))
        else:
            recs[key] = {"adherence": dict(rec.get("adherence", {})), "quality": dict(rec.get("quality", {})), "n": rec.get("n")}


def get(split, cond, ctrl, method, res, cond_res=512, subset="", via=""):
    return recs.get((split, cond, ctrl, method, res, cond_res, subset, via))


def A(r, k, nd=3):
    v = None if r is None else r["adherence"].get(k)
    return "" if v is None else (f"{v:.{nd}f}" if isinstance(v, float) else str(v))


def Q(r, k, nd=1):
    v = None if r is None else r["quality"].get(k)
    return "" if v is None else f"{v:.{nd}f}"


def dag(r):
    return "" if r is None else f"{r['adherence']['f1']:.3f}‡"


L = ["# BASELINES.md: the numbers a CGD variant has to beat", "",
     "Auto-generated by `bench/make_baselines.py` from `results/bench/`; regenerate after every new record. All rows decode the SAME cached "
     "latents (seed 0, 28 steps, guidance 3.5, 512 generation). Metric conventions: BENCHMARK v1.11 / `update.md`. "
     "Canny F1 = tolerant F1 (one condition pixel: 1 px at the 512 view, 4 px at native 2048); strict = pixel-exact (512 anchor). "
     "‡ = bicubic x4 upsample of a 512-native output (the interpolation route, NOT a native output). PiD = released 4-step distilled student; "
     "teacher = undistilled v1.5 (25 steps, CFG 5). K/28 = generator steps before the decoder takes over (K = 24 is the table setting).", ""]

# ---------------------------------------------------------------- A. main benchmark
L += ["## A. Main benchmark: 512-generation, condition = the 512 map (canny + depth on multigen5k, n = 5000; seg on ade20k_val2k, n = 2000)", "",
      "| row | Canny F1 @512 ↑ | Canny F1 @2048 ↑ | strict F1 @512 | Depth MSE ↓ | Depth RMSE ↓ | Seg mIoU ↑ | FID ↓ | pFID ↓ | MUSIQ @512 ↑ | MANIQA @512 ↑ | LPIPS vs source ↓ |",
      "|---|---|---|---|---|---|---|---|---|---|---|---|"]


def row(label, c512, c2048, d512, s512, dagger=None):
    f2048 = A(c2048, "f1") if c2048 is not None else (dag(dagger) if dagger is not None else "n/a")
    L.append("| " + " | ".join([label, A(c512, "f1"), f2048, A(c512, "f1_strict"), A(d512, "mse", 1), A(d512, "rmse", 2), A(s512, "miou", 1),
                                Q(c512, "fid", 2), Q(c512, "pfid", 2), Q(c512, "musiq", 1), Q(c512, "maniqa", 3), Q(c512, "lpips", 3)]) + " |")


M = "multigen5k"; ADE = "ade20k_val2k"
row("Real image", get(M, "canny", "", "real", 512), None, get(M, "depth", "", "real", 512), get(ADE, "seg", "", "real", 512), dagger=get(M, "canny", "", "real", 2048, via="ref"))
row("VAE round trip (decode ceiling)", get(M, "canny", "", "vae_roundtrip", 512), None, get(M, "depth", "", "vae_roundtrip", 512), get(ADE, "seg", "", "vae_roundtrip", 512), dagger=get(M, "canny", "", "vae_roundtrip", 2048, via="ref"))
row("PiD round trip (generative ceiling; 0.80 = practical ceiling of the 2048 column)", get(M, "canny", "", "pid_roundtrip", 512), get(M, "canny", "", "pid_roundtrip", 2048), get(M, "depth", "", "pid_roundtrip", 512), get(ADE, "seg", "", "pid_roundtrip", 512))
for ctrl, name in CTRL.items():
    L.append(f"| **{name}** | | | | | | | | | | | |")
    row(f"&nbsp;&nbsp;+ VAE decode (the controller as published)", get(M, "canny", ctrl, "vae", 512), None, get(M, "depth", ctrl, "vae", 512), get(ADE, "seg", ctrl, "vae", 512), dagger=get(M, "canny", ctrl, "vae", 2048, via="ref"))
    for K in (28, 24, 16):
        row(f"&nbsp;&nbsp;+ vanilla PiD, K={K}" + (" **(the row to beat at K=24)**" if K == 24 else ""), get(M, "canny", ctrl, f"pid_k{K}", 512), get(M, "canny", ctrl, f"pid_k{K}", 2048), get(M, "depth", ctrl, f"pid_k{K}", 512), get(ADE, "seg", ctrl, f"pid_k{K}", 512))
        if get(M, "canny", ctrl, f"pidt_k{K}", 512) or get(M, "canny", ctrl, f"pidt_k{K}", 512, subset="subset500"):
            r5 = get(M, "canny", ctrl, f"pidt_k{K}", 512) or get(M, "canny", ctrl, f"pidt_k{K}", 512, subset="subset500")
            sub = "" if get(M, "canny", ctrl, f"pidt_k{K}", 512) else "subset500"
            row(f"&nbsp;&nbsp;+ vanilla PiD teacher, K={K}" + (f" (n = 500)" if sub else ""), r5, get(M, "canny", ctrl, f"pidt_k{K}", 2048, subset=sub), get(M, "depth", ctrl, f"pidt_k{K}", 512, subset=sub), None)
L += ["", "Notes: FID / pFID / no-ref / LPIPS come from the CANNY run of each controller (its depth run is a different set of images). Seg mIoU exists only for "
      "EasyControl (released seg LoRA); OminiControl's seg adapter is optional (red text in the paper). Depth and seg are flat across resolutions by construction "
      "(scorers resize internally). Paired bootstrap 95% CIs on 5000 images are within ±0.003 F1 (`bench/paired_ci.py`).", ""]

# ---------------------------------------------------------------- B. native condition
L += ["## B. Native-condition setting: the DECODER receives the 2048 edge map (multigen5k canny, tolerance 1 px at 2048)", "",
      "The 2048 condition is Canny of the PiD round trip of the real image (`multigen5k/conditions/canny2048`), so the round trip is the reference (1.0). "
      "Generator input unchanged (512 map). Score with `harness.py --res 2048 --cond-res 2048`.", "",
      "| row | Canny F1 @2048 vs the 2048 condition ↑ |", "|---|---|"]
for label, r in [("PiD round trip (reference)", get(M, "canny", "", "pid_roundtrip", 2048, cond_res=2048)),
                 ("Real image, bicubic x4 ‡", get(M, "canny", "", "real", 2048, cond_res=2048, via="ref")),
                 ("VAE round trip, bicubic x4 ‡", get(M, "canny", "", "vae_roundtrip", 2048, cond_res=2048, via="ref"))]:
    L.append(f"| {label} | {A(r, 'f1')} |")
for ctrl, name in CTRL.items():
    L.append(f"| **{name}** | |")
    L.append(f"| &nbsp;&nbsp;+ VAE decode, bicubic x4 ‡ | {A(get(M, 'canny', ctrl, 'vae', 2048, cond_res=2048, via='ref'), 'f1')} |")
    for K in (28, 24, 16):
        L.append(f"| &nbsp;&nbsp;+ vanilla PiD, K={K}{' **(to beat)**' if K == 24 else ''} | {A(get(M, 'canny', ctrl, f'pid_k{K}', 2048, cond_res=2048), 'f1')} |")
        rt = get(M, "canny", ctrl, f"pidt_k{K}", 2048, cond_res=2048) or get(M, "canny", ctrl, f"pidt_k{K}", 2048, cond_res=2048, subset="subset500")
        if rt:
            L.append(f"| &nbsp;&nbsp;+ vanilla PiD teacher, K={K} | {A(rt, 'f1')} |")
L.append("")

# ---------------------------------------------------------------- C. subject
L += ["## C. Subject (DreamBench, 750 pairs, OminiControl subject LoRA, 512 view)", "", "| row | DINO ↑ | CLIP-I ↑ | CLIP-T ↑ | MUSIQ ↑ |", "|---|---|---|---|---|"]
for label, m in [("VAE decode", "vae"), ("vanilla PiD, K=28", "pid_k28"), ("vanilla PiD, K=24 (to beat)", "pid_k24"), ("vanilla PiD, K=16", "pid_k16")]:
    r = get("dreambench750", "subject", "omini", m, 512)
    L.append(f"| {label} | {A(r, 'dino')} | {A(r, 'clip_i')} | {A(r, 'clip_t')} | {Q(r, 'musiq')} |")
L.append("")

# ---------------------------------------------------------------- D. sweep
sw = R / "sweep" / "SUMMARY.md"
if sw.exists():
    L += ["## D. Condition-scale sweep (canny dev-200, OminiControl; fig:ceiling)", ""] + sw.read_text().strip().splitlines()[2:] + [""]

# ---------------------------------------------------------------- E. dev-200 gate
dv = ROOT / "results" / "dev200_summary.md"
if dv.exists():
    L += ["## E. Dev-200 loop (method selection; NOT paper numbers). Gate = beat vanilla PiD at the same K in tolerant F1 at 512 AND 2048, MUSIQ not lower, LPIPS not worse", ""] + dv.read_text().strip().splitlines() + [""]

# ---------------------------------------------------------------- F. teacher (subset500 paired)
has_t = any(k[3].startswith("pidt") for k in recs)
if has_t:
    L += ["## F. Student vs teacher on subset500 (paired; the teacher is the checkpoint CGD trains on)", "",
          "| decoder | K | Canny F1 @512 | Canny F1 @2048 | Canny F1 @2048 vs 2048 cond | Depth RMSE | MUSIQ @512 | LPIPS |", "|---|---|---|---|---|---|---|---|"]
    for who, lab in [("pid", "student"), ("pidt", "teacher")]:
        r = get(M, "canny", "", f"{who}_roundtrip", 512, subset="subset500"); r2 = get(M, "canny", "", f"{who}_roundtrip", 2048, subset="subset500")
        if r:
            L.append(f"| round trip, {lab} | n/a | {A(r, 'f1')} | {A(r2, 'f1')} |  | {A(get(M, 'depth', '', f'{who}_roundtrip', 512, subset='subset500'), 'rmse', 2)} | {Q(r, 'musiq')} | {Q(r, 'lpips', 3)} |")
    for K in (28, 24, 16):
        for who, lab in [("pid", "student"), ("pidt", "teacher")]:
            r = get(M, "canny", "omini", f"{who}_k{K}", 512, subset="subset500")
            if r:
                L.append(f"| OminiControl + PiD {lab} | {K} | {A(r, 'f1')} | {A(get(M, 'canny', 'omini', f'{who}_k{K}', 2048, subset='subset500'), 'f1')} | "
                         f"{A(get(M, 'canny', 'omini', f'{who}_k{K}', 2048, cond_res=2048, subset='subset500'), 'f1')} | {A(get(M, 'depth', 'omini', f'{who}_k{K}', 512, subset='subset500'), 'rmse', 2)} | {Q(r, 'musiq')} | {Q(r, 'lpips', 3)} |")
    L.append("")

# ---------------------------------------------------------------- G. efficiency
eff = R / "efficiency.json"
if eff.exists():
    L += ["## G. Efficiency (one H200, median per image)", "", "| output | pipeline | gen res | gen steps | dec steps | latency s | peak GB |", "|---|---|---|---|---|---|---|"]
    for e in json.load(open(eff)):
        L.append(f"| {e.get('output')} | {e.get('pipeline')} | {e.get('gen_res')} | {e.get('gen_steps')} | {e.get('dec_steps')} | {('%.2f' % e['latency_s']) if e.get('latency_s') else e.get('note', '')} | {('%.1f' % e['peak_mem_gb']) if e.get('peak_mem_gb') else ''} |")
    L.append("")

# ---------------------------------------------------------------- H. the rule
L += ["## H. What \"beating the baseline\" means", "",
      "1. Decode the SAME cached latents (`latents/<controller>/<condition>/<sid>.pt`, x_0 + x_t@24 + x_t@16) at the same truncation point K as the row you compare with.",
      "2. Score with `python bench/eval_variant.py --name <yourname> --gen-dir <dir of 2048 PNGs> --controller omini --condition canny --k 24` "
      "(runs the harness at the 512 view and at native 2048, both condition definitions, and prints the deltas and paired CIs against this file).",
      "3. Pass = tolerant canny F1 higher than vanilla PiD at the same K at BOTH the 512 view and native 2048, with MUSIQ not lower and LPIPS not worse; "
      "depth RMSE not worse; and, if you use the 2048 condition, the native-condition F1 (Section B) is your extra headroom.",
      "4. Compare a teacher-based CGD against the TEACHER rows (Section F) for the exact ablation; the student rows are the deployed decoder.",
      "5. Never report dev-200 numbers as paper numbers; the paper uses the full sets (Sections A-C)."]
(ROOT / "BASELINES.md").write_text("\n".join(L) + "\n")
json.dump({"|".join(map(str, k)): v for k, v in recs.items()}, open(R / "baselines.json", "w"), indent=1)
print(f"wrote {ROOT / 'BASELINES.md'} ({len(recs)} records) and results/bench/baselines.json")
